services:
  streamlit:
    build: .
    ports:
      - "${STREAMLIT_PORT}:8501"
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - STREAMLIT_PORT=${STREAMLIT_PORT}
    container_name: streamlit_service
    command: streamlit run app/streamlit_ui.py
    networks:
      - app-network
networks:
  app-network:
    driver: bridge